language: java
jdk:
- openjdk7
- oraclejdk7
deploy:
  provider: gae
  default: true
  project: cvsi-backend
  keyfile: cvsi-travis-credentials.json
install:
- ./gradlew :backend:assemble
script:
- ./gradlew :backend:check
