language: java
jdk:
- openjdk7
- oraclejdk7
deploy:
  provider: gae
  default: true
  project: cvsi-backend
  keyfile: cvsi-travis-credentials.json
before_install:
- openssl aes-256-cbc -K $encrypted_117654b73dc1_key -iv $encrypted_117654b73dc1_iv
  -in cvsi-travis-credentials.json.enc -out .\\cvsi-travis-credentials.json -d
